# Lab 5 - Part 2

In the first part of this lab, you were tasked with implementing a Matrix class based on the matrix operations you implemented in Exam 1.

In this part of the lab you will test your Matrix implementation by comparing to the `numpy` which is the most commonly used python library for matrices and tensors (high dimensional matrices).

## Matrix Library

*Exercise 1:* You implemented the first part of this lab in a python notebook. Use the new button from the Jupyter file browser page to create and edit a new text file named "matrix.py" in the "Lab-5" directory where this current notebook is running. Copy and paste your matrix implementation into this file. You may use a different text editor if you like. Make sure you add, commit, and push your `matrix.py` file when you submit your solutions to this lab.

*Exercise 2:* Use python `import` to import your library into this notebook. Note that if there is a problem with your "matrix.py" file, you will get an error during the import. You can correct this error by editting the file and running the import cell again. But if the import succeeds, using import will not re-read the file. So if you edit the file after a successful import, you will need to either restart this notebook or use the python `reload` built-in to reload your matrix module.


In [1]:
import Matrix

*Exercise 3:* Demonstrate the basic properties of matrices with your matrix class by creating two 2 by 2 example matrices using your Matrix class and illustrating the following:

$$
(AB)C=A(BC)
$$
$$
A(B+C)=AB+AC
$$
$$
AB\neq BA
$$
$$
AI=A
$$

In [19]:
a= [[1,1],[1,1]]
b= [[2,1],[3,4]]
c= [[3,4],[2,3]]
A=Matrix.Matrix(A)
B=Matrix.Matrix(B)
mult_AB=A.__matmult__(b)
mult_AC=A.__matmult__(c)
Add_BC=list(b+c)
A_B=A.__matmult__(b)
A_C=A.__matmult__(c)
B_C=B.__matmult__(c)
 

AttributeError: Matrix instance has no attribute '__getitem__'

## Matrices with `numpy`
`numpy` is very well [documented](https://docs.scipy.org/doc/numpy/reference/index.html). You can find a list of linear algebra operations in `numpy` [here](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html). A more general and detailed description of linear algebra with `numpy` and `scipy` (which implements same routines) can be found [here](https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html).


In [8]:
import numpy as np

A = np.array([[4.,5.],[-2.,-1.]])
y = np.array([12.,2.])

print "A:"
print A
print "y"
print y

A_inv=np.linalg.inv(A)

print "Inverse of A:"
print A_inv

print "A * A_inverse:"
print np.matmul(A,A_inv)

print "Identity:"
print np.eye(*A.shape)

x= np.matmul(A_inv,y)

print "Solution: x="
print x

print "Check solution: Ax="
print np.matmul(A,x)
print y==np.matmul(A,x)

A:
[[ 4.  5.]
 [-2. -1.]]
y
[12.  2.]
Inverse of A:
[[-0.16666667 -0.83333333]
 [ 0.33333333  0.66666667]]
A * A_inverse:
[[ 1.00000000e+00  1.11022302e-16]
 [-5.55111512e-17  1.00000000e+00]]
Identity:
[[1. 0.]
 [0. 1.]]
Solution: x=
[-3.66666667  5.33333333]
Check solution: Ax=
[12.  2.]
[ True False]


*Exercise 3:* Following the numpy example above, demonstrate that your matrix class reproduces the functionality of numpy. If you were unable to implement the inverse method you may use numpy's inverse. Note that the syntax for your matrix module may be different than numpy. 

In [12]:
A = Matrix.Matrix(2,2)
A_inv= Matrix.Matrix(2,2)
B = np.array([[4.,5.],[-2.,-1.]])
y= Matrix.Matrix(2,2)
y.M=[[12.,2.]]
A.M=[[4.,5.],[-2.,-1.]]
print "A:"
print A.M
print "y"
print y.M

B_inv=list(np.linalg.inv(B))

print "Inverse of A:"
print np.linalg.inv(B)

print "A * A_inverse:"
print A.__matmult__(B_inv)

print "Identity:"
print A.eye()

A_inv.M=B_inv
z=list(y.M)
#x= A_inv.__matmult__(z)

print "Solution: x="
#print x
x=[[-3.66666667,  5.33333333]]

print A.__matmult__(x)

TypeError: __init__() takes exactly 2 arguments (3 given)

## Matrix Elements
Consider an arbitrary matrix $A$:

\begin{equation*}
A_{m,n} = 
 \begin{pmatrix}
  a_{11} & a_{12} & \cdots & a_{1n} \\
  a_{21} & a_{22} & \cdots & a_{2n} \\
  \vdots  & \vdots  & \ddots & \vdots\\
  a_{m1} & a_{m2} & \cdots & a_{mn} 
\end{pmatrix}
\end{equation*}

we define the columns as $a_j=A_{:,j}$:

\begin{pmatrix} 
| & | &  &|\\
a_1 & a_2 & \dots &\ a_n\\
| & | &  &|
\end{pmatrix}

and rows $a^T_i = A_{i,:}$:

\begin{pmatrix} 
- & a^T_1 & -\\
- & a^T_2 & -\\
 & \vdots & \\
- & a^T_3 & -\\
\end{pmatrix}

or in `numpy`:


In [ ]:
# Make a random matrix
A = np.random.rand(10,5)

print "A:"
print A
print "A shape:", A.shape

print "A columns:"
for i in range(A.shape[1]):
    print A[:,i]

print "A rows:"
for j in range(A.shape[0]):
    print A[j,:]
    # Note you can also use A[j]

*Exercise 4:* Add a new random feature to your matrix library and demonstrate the same numpy functionality as above. For a bit of extra credit, implement slicing in your override of `__getitem__` method in your matrix class.

In [13]:
A = Matrix.Matrix(2,2)
A.M=A.rand(10,5)
print "A:"
print A.M
print "A shape:", A.Shape()
shape=A.Shape()
print "A columns:"
for i in range(shape[1]):
    print A.column(i)

print "A rows:"
for j in range(shape[0]):
    print A.row(j)

TypeError: __init__() takes exactly 2 arguments (3 given)

# Matrix Operations

* Transpose: $(A^T)_{ij} = A_{ji}$
* Sum (elementwise): $C_{ij} = A_{ij} + B_{ij}$
* Elementwise product: $C_{ij} = A_{ij} B_{ij}$
* Matrix product: $C=A \cdot B$: $C_{ij} = \sum_{k} A_{ik} B_{kj}$.
   * Note than if size of $A$ is $n \times m$ then $B$ has to be of size $m \times k$ and the resulting matrix will be of size $n \times k$.
   * Good way to visualize product:
    \begin{equation*}
    AB=
\begin{pmatrix} 
- & a_1 & -\\
- & a_2 & -\\
 & \vdots & \\
- & a_m & -\\
\end{pmatrix} 
\begin{pmatrix} 
| & | &  &|\\
b_1 & b_2 & \dots &\ b_n\\
| & | &  &|
\end{pmatrix}=
\begin{pmatrix}
a^T_1b_1 & a^T_1b_2 & \dots & a^T_1b_n\\
a^T_2b_1 & a^T_2b_2 & \dots & a^T_2b_n\\
\vdots & \vdots & \ddots & \vdots \\
a^T_mb_1 & a^T_mb_2 & \dots & a^T_mb_n
\end{pmatrix}
\end{equation*}

In [ ]:
A = np.random.rand(5,4) 
print "A:"
print A

print "A Transpose:"
print A.transpose()

B = np.random.rand(5,4) 
print "B:",
print B

print "A+B:"
print A+B

print "A*B:"
print A*B

# For Matrix Multiply we need correct size B
B1 = np.random.rand(4,5) 

print "Matrix Multiply: A (dot) B1:"
print np.matmul(A,B1)

*Exercise 5:* Demonstrate basic matrix operations above with your matrix library.

In [ ]:
A = Matrix.Matrix(5,4)
A_rand=A.rand(5,4)
print "A:"
print A_rand

print "A Transpose:"
print Matrix.Matrix.transpose(A_rand)

B = Matrix.Matrix(5,4)
B_rand=B.rand(5,4)
print "B:",
print B_rand

print "A+B:"
print A+B_rand

print "A*B:"
print A.elementmult(B_rand)

 
B1 = Matrix.Matrix(4,5) 
B1.M=B1.rand(4,5)
print "Matrix Multiply: A (dot) B1:"
print A.__matmult__(B1.M)

## Vector Products

* Dot product: $x\cdot y = x^T y = \sum_{i=1}^n x_i y_i$
* Other product: 
\begin{equation*}
\begin{pmatrix} x_1\\x_2\\ \vdots \\x_m \end{pmatrix} \begin{pmatrix} y_1&y_2& \dots &y_n\end{pmatrix} =
\begin{pmatrix}
x_1y_1 & x_1y_2 & \dots & x_1y_n\\
x_2y_1 & x_2y_2 & \dots & x_2y_n\\
\vdots & \vdots & \ddots & \vdots \\
x_my_1 & x_my_2 & \dots & x_my_n
\end{pmatrix}
\end{equation*}

In `numpy`:

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print "x (dot) y:"
print np.dot(x,y)

print "Other product:"
print np.outer(x,y)

*Exercise 6:* Demonstrate vector product operations above with your matrix library.

In [2]:
A=[1,2,3]
B=[4,5,6]
x=Matrix.Vector(A,B)
 
print "x (dot) y:"+str(x.dot())
print "Other product:"+str(x.outer())

x (dot) y:32
Other product:[[4, 5, 6], [8, 10, 12], [12, 15, 18]]


## Norms
* $l=1$ Norm: $\parallel x \parallel_1 = \sum_{i=1}^{n}|x_i|$
* $l=2$ Norm: $\parallel x \parallel_2 = \sqrt{\sum_{i=1}^{n}x_i^2}$
* $l=p$ Norm: $\parallel x \parallel_p = \left(\sum_{i=1}^{n}x_i^p\right)^\frac{1}{p}$
* $l=\infty$ Norm: $\parallel x \parallel_\infty = \max_i |x_i|$
* Law of cosines: $x \cdot y = $\parallel x \parallel_2 $\parallel y \parallel_2 \cos{\theta}$

In `numpy`:

In [14]:
x=[1,2,3]
for i in range(10):
    print i,np.linalg.norm(x,i)

0 3.0
1 6.0
2 3.7416573867739413
3 3.3019272488946263
4 3.1463462836457885
5 3.077384885394063
6 3.043010262919305
7 3.0246626009458444
8 3.014443335890572
9 3.0085886861624296


*Exercise 7:* Test the norm implementationth your matrix library.

In [15]:
x=Matrix.Vector()
A=[1.0,2.0,3.0]
for i in range(10):
    print i,x.norm(A,i)

0 3.0
1 6.0
2 3.74165738677
3 3.30192724889
4 3.14634628365
5 3.07738488539
6 3.04301026292
7 3.02466260095
8 3.01444333589
9 3.00858868616
